Affichage des durées de ProgressDashboard via les macros twig
YesWiki/yeswiki-extension-lms pull request #24
Opened 2021-03-26 20:07 UTC by acheype

use CarbonInterval for duration in the CourseStucture objects & datetime macros in ProgressDashboard

Il y avait déjà le système de macro twig pour gérer l'affichage des date/durée mis en place. J'avais mis à jour le LearnerDashboard, mais il restait le ProgressDashboard qui passait par une bidouille de contrôleur. 
Amélioration liée : maintenant le getDuration des CoursesStructures rend un CarbonInterval et plus un int.

Vu que tu es en plein dev, @J9rem j'ai créé une branche afin d'être sûr que ça ne pose pas de soucis. J'attends ton OK pour merger. Normalement, ça ne devrait pas bcp impacter tes devs.

2021-03-26 21:46 UTC, J9rem requested changes
Belle proposition, nous allons gagner en lisibilité!
J'apprécie que tu passes par une PR car il y a des modifications nécessaires avant que je puisse valider.
- Il reste un `'formatter' => $this->getTwigFormatter()` dans le courseController L 209 qui me semble de trop (sinon bug)
- et dans le LearnerDashBoardManager L 212
je remplacerai `$activityDuration = this->dateManager->createIntervalFromMinutes($activity->getDuration());`
par 
`$activityDuration = $activity->getDuration();` pour le cas où 
`$this->wiki->config['lms_config']['use_only_custom_elapsed_time'] = false `

Peux-tu procéder aux modifications pour que je puisse m'assurer que ça n'engendre pas de bugs ?

2021-03-26 21:46 UTC, J9rem commented on libs/Course.php
> +            $this->duration = $count->totalMinutes != 0 ? $count->cascade() : null;
Est-ce que tu peux m'expliquer la raison de `$count->totalMinutes != 0` ?
car ça ne me choque pas d'avoir un CarbonInterval avec une valeur de 0.
Mais je ne demande pas de changement du code.

2021-03-27 11:06 UTC, acheype commented on libs/Course.php
> +            $this->duration = $count->totalMinutes != 0 ? $count->cascade() : null;
dans `displayTime` de `datetime-macros.twig`, il y a

> {% if dateInterval is null %}
>        -
> ...

pour moi s'il y a une durée elle est positive, sinon c'est qu'il n'y en a pas. On aurait pu aussi mettre le test de la macro `displayTime` sur 0 mais dans le cas actuel, on peut écrire  '0 min' s'il on en a besoin.

2021-03-27 11:20 UTC, acheype commented
Pour le reste, j'ai fais les rectifs, merci.

J'avais zappé que j'avais déjà refactoré le `renderModuleCard` avec l'ancien twigFormatter. J'ai mis à jour cette partie et j'ai dû remettre de nouvelles fonctions dans DateManager. Tu feras gaffe car le nom de certaines fonctions ont changé pour prendre en compte plus de formats.

Tu me diras si c'est bon pour toi @J9rem ?
Et j'ai vu que tu avais cherrypické le premier commit de la PR dans lms21-spec1-phase1-j3rem. Peux-tu le supprimer et te rebaser une fois qu'on merge celle-ci ?

2021-03-27 12:23 UTC, J9rem commented
>Et j'ai vu que tu avais cherrypické le premier commit de la PR dans lms21-spec1-phase1-j3rem. Peux-tu le supprimer et te rebaser une fois qu'on merge celle-ci ?

Oui c'est prévu, j'attends la fusion de cette branche.
Je te relie ceci d'ici lundi matin ;-)

2021-03-28 08:28 UTC, J9rem approved these changes
@acheype belle bonification du code.
J'attends que tu fasses la fusion dans la branche Doryphore pour faire le rebase sur la branche `lms21-spec1-phase1-j3rem`.

Je t'ai fais une proposition d'amélioration du code pour le stockage des durées.
Je te laisse voir si tu l'inclues de suite. J'en aurai besoin pour le suivi des webinaires afin d'éviter des erreurs de stockage d'informations.

2021-03-28 08:28 UTC, J9rem commented on services/DateManager.php
>          return $duration->format(self::TIME_FORMAT_WITH_COLONS);
```suggestion
        // create new CarbonInterval to set total hours without cascade
        // Difference between 2021-01-01 00:00:00 and 2021-01-02 01:05:00 should give 25:05:00
        // whereas $duration->format(self::TIME_FORMAT_WITH_COLONS); gives 01:05:00
        return CarbonInterval::hours($duration->totalHours)
                    ->minutes($duration->minutes)
                    ->seconds($duration->seconds)
                    ->format(self::TIME_FORMAT_WITH_COLONS);
```

SI tu es d'accord, @acheype , je proposerais bien cette amélioration. (Les commentaires expliquent la raison).

2021-03-28 19:16 UTC, acheype commented
Oky, j'ai intégré vu que ça corrige les durées de plus d'un jour.

J'ai changé des petits trucs aussi : adapter quelques noms de fonctions et supprimer la possibilité de mettre `null` à l'appel pour avoir la date courante. Je trouve finalement que c'est plus lisible de laisser l'utilisateur appeler le format avec un `Carbon::now()`.

Dis-moi si ça te va avant que je merge.

2021-03-29 07:25 UTC, J9rem commented
Tout est bon, ce sont des modifs. mineurs. T peux fusionner.
Comme dit souvent Florian, le mieux est l'ennemi du bien.

2021-03-29 08:12 UTC, merged